// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  subgraphsSidebar: [{ type: 'autogenerated', dirName: 'subgraphs' }],
  conceptsSidebar: [{ type: 'autogenerated', dirName: 'concepts' }],
  contractsSidebar: [{ type: 'autogenerated', dirName: 'contracts' }],
};

module.exports = sidebars;
